@extends('layouts.app')

@section('content')
  <h2>Help</h2>
  <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi, officia mollitia aliquid iusto reiciendis optio debitis non labore corrupti incidunt ipsa cum ipsum consequatur. Magni dolores itaque inventore cupiditate voluptates aspernatur, optio dolorem culpa nulla aliquam, nisi, facere quaerat perspiciatis quidem illo unde totam est. Adipisci, voluptatum numquam quidem optio consequuntur atque at quos laboriosam earum ipsa corporis porro facere ullam qui velit dolor nemo impedit beatae temporibus perspiciatis excepturi doloremque illo magni. Voluptatem delectus dicta at soluta illum similique consequatur nesciunt excepturi veritatis culpa commodi voluptas veniam, numquam eum, suscipit est consequuntur corrupti nulla accusamus enim nemo ut.</p>
  <br>
  <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sapiente quisquam temporibus eligendi atque labore laudantium! Debitis, exercitationem molestias. Sed harum praesentium optio, similique voluptatum nihil delectus velit ullam soluta eveniet aperiam ut vel aliquam, sequi esse nisi voluptatem fugit excepturi in aspernatur tempora quod culpa, unde dolorum. Accusantium a ad amet soluta distinctio dolores officiis esse, minima sunt. Ducimus dicta quos eligendi quisquam sed tempore dolorum?</p>
  <br>
  <hr>
  <div id="help">  
      <img class="item" src="../images/screenshot.png" alt="Screenshot1">
      <img class="item" src="../images/screenshot.png" alt="Screenshot2">
      <img class="item" src="../images/screenshot.png" alt="Screenshot3">
  </div>
  <hr>
  <br>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur, quam? Velit, tenetur eaque. Nulla soluta magni distinctio delectus, deserunt ad sunt similique laudantium, nihil deleniti nostrum, officia eveniet quasi modi aut et laborum amet ab? Laboriosam vero sequi neque aut deleniti aspernatur ipsum, laborum rem, eos quas beatae ad? Nisi nihil error facere optio quo perferendis dolorem alias consectetur atque repellat, libero cumque obcaecati distinctio mollitia molestiae repudiandae qui? Debitis fugiat exercitationem consectetur voluptates et facilis minus quis repudiandae officiis unde eius commodi veritatis sapiente magni laboriosam tempore corrupti, reiciendis sequi saepe maiores pariatur ad soluta? Quibusdam labore itaque quisquam asperiores fugiat deserunt sint delectus magnam omnis. Aliquid nulla repellendus dolores obcaecati excepturi iusto veritatis nobis temporibus. Non ipsam numquam deserunt rerum. Quisquam, itaque a!</p>
  <br>
  <hr>
  <div id="help">  
    <img class="item" src="../images/screenshot.png" alt="Screenshot1">Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi soluta deserunt quis voluptas laudantium aperiam corporis, ut ipsam nisi quas, assumenda dolorem ducimus, pariatur architecto est beatae fuga similique? Ex quisquam perferendis corrupti laudantium placeat ducimus expedita cumque incidunt minus ipsum, distinctio itaque maiores quibusdam optio totam nobis adipisci illo! Rerum sequi velit, dolores numquam placeat excepturi nam assumenda aliquid sapiente impedit iusto obcaecati est officia, eaque reiciendis corporis voluptate qui libero nemo commodi! Unde, quia! Aspernatur eos perferendis quisquam veritatis culpa cupiditate expedita aliquam quae repellat quod vel consequatur quos, ratione voluptate. Esse ad nam adipisci ipsam asperiores deleniti.
    <img class="item" src="../images/screenshot.png" alt="Screenshot2">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias vel ea minus reiciendis eos, nobis repellendus illo quia, debitis ducimus, suscipit nostrum ratione architecto numquam enim ex eius inventore minima hic. Provident cupiditate, fugiat qui quia non omnis quis. Non ducimus sunt optio autem beatae tempore! Omnis sunt dolor laudantium, cumque eius dicta nostrum perspiciatis ipsa nemo unde fuga at suscipit nam ullam asperiores numquam atque velit dolore vero! Corrupti nemo magni, hic officia minus unde molestiae expedita recusandae? Laborum illum excepturi dolores ab quia soluta earum aliquid atque nesciunt recusandae enim, facere autem voluptate beatae voluptates doloremque ducimus sunt.
    <img class="item" src="../images/screenshot.png" alt="Screenshot3">Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum iusto reprehenderit adipisci atque quasi perferendis deleniti, dolorum voluptatum quisquam beatae impedit tenetur ipsam facilis provident placeat? Labore in atque sapiente, aliquam rerum explicabo suscipit, dolorem dignissimos amet facilis laudantium temporibus earum debitis, vitae tempore velit optio ut voluptatibus cumque magni. Aliquam ullam ad doloremque impedit officia laborum consequuntur animi placeat ipsa tenetur repellat accusamus maiores eius quos earum, reprehenderit necessitatibus! Qui, ducimus tenetur sed aspernatur deserunt ratione ullam consectetur officiis, nulla nihil consequatur tempora eligendi, eveniet quibusdam iusto hic totam ipsam culpa. Numquam dolorem, aut fugit libero ratione inventore atque!
    <img class="item" src="../images/screenshot.png" alt="Screenshot3">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Blanditiis deserunt soluta id facere, consectetur ipsa provident alias. Exercitationem, earum non nesciunt architecto in voluptatum? Fugiat amet repellendus accusamus ut at sint facilis, aperiam assumenda incidunt commodi deleniti nesciunt expedita excepturi quos ea error, sapiente reiciendis voluptatum sunt in ipsam. Sit vel debitis ab tempora soluta dolore atque, nam obcaecati in cum explicabo alias, ullam fuga natus ducimus iure mollitia perspiciatis doloremque officiis magnam assumenda, quaerat numquam eius laboriosam! Pariatur explicabo atque suscipit aliquid, maxime tempora beatae odit, optio cupiditate nesciunt quidem ab culpa quis quia molestias reiciendis deleniti sint in.
  </div>
  <hr>
  <br>
  <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aliquid vero asperiores quod explicabo odit. At vel similique adipisci illo debitis impedit hic, ratione id beatae, labore sed omnis ea nobis itaque architecto accusamus voluptatum necessitatibus laudantium soluta eum quae ducimus. At eum perferendis nulla iste odit nihil maiores rem asperiores autem provident! Itaque obcaecati ex sapiente incidunt pariatur ea! Dicta animi obcaecati voluptates eaque. Veritatis nulla, ullam tempora accusantium necessitatibus maiores quasi rerum, at quae eligendi aperiam fuga ducimus ex similique voluptatum harum labore, ab aliquam! Harum cum adipisci voluptatem laboriosam quasi deleniti. Nemo iure asperiores aliquid illo molestias? Beatae, deleniti! Deserunt voluptatem quaerat eligendi repellat laudantium laboriosam consectetur accusamus nihil autem, labore odio, recusandae fugiat quidem debitis quod vero facere provident inventore excepturi quo perferendis architecto sapiente! Asperiores dignissimos consequuntur eos a laborum quidem, excepturi fugiat laboriosam perferendis vitae, sit repudiandae cumque culpa veritatis minus exercitationem cupiditate? Adipisci repellat ut nobis nesciunt est vero quos consequuntur nam, odio saepe odit officiis suscipit iste, at eveniet quia earum doloribus aliquam aspernatur distinctio facilis commodi voluptatem soluta dolore! Quos doloremque dolor atque fuga deserunt modi suscipit maxime ipsam aspernatur. Pariatur blanditiis debitis omnis numquam asperiores officiis! Voluptates ab corporis at consequatur.</p>
  @endsection

